const API='https://mantledb.sh/v2/painel60-abaco-hs-20260819-9f4c8d/state';
const initialState={version:2,updatedAt:null,metrics:[
{id:'sales',label:'Vendas',target:70,unit:'%',direction:'gte',description:'da meta do período vendida / contratada'},
{id:'coverage',label:'Coverage',target:3,unit:'x',direction:'gte',description:'o gap remanescente para a meta'},
{id:'rtc',label:'RTC',target:90,unit:'%',direction:'gte',description:'dos deals ativos com RTC completo e mantido'},
{id:'forecast',label:'Forecast',target:80,unit:'%',direction:'gte',description:'de accuracy entre Commit e realizado'},
{id:'croTouch',label:'CRO Touch',target:80,unit:'%',direction:'lte',description:'dos deals com atuação pessoal do CRO'},
{id:'people',label:'People',target:100,unit:'%',direction:'gte',description:'do time com 1:1 quinzenal + ≥85% dos compromissos'},
{id:'cs',label:'Customer Success',target:100,unit:'%',direction:'gte',description:'da base segmentada + ≥80% dos Tier 1 com plano'},
{id:'marketing',label:'Marketing',target:100,unit:'%',direction:'gte',description:'das iniciativas com tracking + pipeline mensurado'}],weekly:[],people:['Fabio','Alex','Vitor','Vinicius','Marcela','Gabriela','Bianca'].map(name=>({name,oneOnOnes:[false,false]})),croClients:[]};
let state=structuredClone(initialState), chart=null, saving=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function fmt(v,u){if(v===null||v===undefined||v==='')return '—';const n=Number(v);return u==='%'?`${trim(n)}%`:u==='x'?`${trim(n)}x`:`${trim(n)} ${u||''}`.trim()}
function trim(n){return Number.isInteger(n)?String(n):n.toFixed(1).replace('.',',')}
function targetPrefix(m){return m.direction==='lte'?'≤':'≥'}
function latestWeek(){return state.weekly.length?state.weekly[state.weekly.length-1]:null}
function getActual(m){if(m.id==='people' && !latestWeek()){const done=state.people.flatMap(p=>p.oneOnOnes).filter(Boolean).length;return state.people.length?done/(state.people.length*2)*100:0} const w=latestWeek(); return w?.values?.[m.id]??null}
function isOnTarget(m,v){if(v===null||v===undefined||v==='')return false;return m.direction==='lte'?Number(v)<=Number(m.target):Number(v)>=Number(m.target)}
function attainment(m,v){if(v===null||v===undefined||v==='')return null; if(m.direction==='lte'){if(Number(v)<=0)return 100; return Math.min(200,(Number(m.target)/Number(v))*100)}return Math.min(200,(Number(v)/Number(m.target))*100)}
function normalizeState(s){const out={...structuredClone(initialState),...s};out.metrics=(s?.metrics?.length?s.metrics:initialState.metrics).map((m,i)=>({...initialState.metrics[i],...m}));out.weekly=Array.isArray(s?.weekly)?s.weekly:[];out.people=Array.isArray(s?.people)&&s.people.length?s.people:initialState.people;out.croClients=Array.isArray(s?.croClients)?s.croClients:[];return out}
async function load(){setSync('loading');try{const r=await fetch(API,{cache:'no-store'});if(r.ok){state=normalizeState(await r.json());setSync('online')}else if(r.status===404){state=structuredClone(initialState);await save(true)}else throw new Error('HTTP '+r.status)}catch(e){const local=localStorage.getItem('painel60abaco');if(local)state=normalizeState(JSON.parse(local));setSync('offline')}render()}
async function save(silent=false){if(saving)return;saving=true;state.updatedAt=new Date().toISOString();localStorage.setItem('painel60abaco',JSON.stringify(state));setSync('saving');render();try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});if(!r.ok)throw new Error('HTTP '+r.status);setSync('online');if(!silent)toast('Dados atualizados para todos')}catch(e){setSync('offline');if(!silent)toast('Salvo neste navegador; sincronização indisponível')}finally{saving=false}}
function setSync(mode){const dot=$('#syncDot'),lab=$('#syncLabel');dot.classList.toggle('online',mode==='online');lab.textContent=mode==='online'?'Online • dados compartilhados':mode==='saving'?'Salvando…':mode==='loading'?'Conectando…':'Offline • usando cópia local'}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
function render(){renderHome();renderMetrics();renderWeeklyInputs();renderPeople();renderClients();renderHistory();renderChartSelect();renderChart()}
function renderHome(){const w=latestWeek();$('#macroWeek').textContent=w?.name||'—';$('#macroClients').textContent=state.croClients.length;const done=state.people.flatMap(p=>p.oneOnOnes).filter(Boolean).length;$('#macroPeople').textContent=`${done}/${state.people.length*2}`;let targetCount=0;$('#homeKpis').innerHTML=state.metrics.map((m,i)=>{const v=getActual(m);const ok=isOnTarget(m,v);if(ok)targetCount++;return `<div class="kpi-card"><div class="cap">${String(i+1).padStart(2,'0')} ${esc(m.label)}</div><div class="kpi-value">${v===null?`${targetPrefix(m)} ${fmt(m.target,m.unit)}`:fmt(v,m.unit)}</div><div class="kpi-desc">${esc(m.description)}</div><div class="kpi-footer"><span class="badge ${v===null?'empty':ok?'good':'warn'}">${v===null?'Aguardando acompanhamento':ok?'Meta atingida':`Meta ${targetPrefix(m)} ${fmt(m.target,m.unit)}`}</span></div></div>`}).join('');$('#macroOnTarget').textContent=`${targetCount}/8`}
function renderMetrics(){const el=$('#metricInputs');el.innerHTML=state.metrics.map((m,i)=>`<div class="metric-box"><div class="name">${String(i+1).padStart(2,'0')} ${esc(m.label)}</div><div class="metric-row"><input data-metric-target="${m.id}" type="number" step="0.1" value="${m.target}"><input data-metric-unit="${m.id}" value="${esc(m.unit)}" maxlength="8"></div><div style="font-size:11px;color:#71808e;margin-top:8px">${targetPrefix(m)} meta • ${esc(m.description)}</div></div>`).join('')}
function renderWeeklyInputs(){const el=$('#weeklyMetricInputs');el.innerHTML=state.metrics.map((m,i)=>`<div class="metric-box"><div class="name">${String(i+1).padStart(2,'0')} ${esc(m.label)}</div><div class="field"><input data-week-value="${m.id}" type="number" step="0.1" placeholder="Realizado (${esc(m.unit)})"><span style="font-size:11px;color:#71808e">Meta ${targetPrefix(m)} ${fmt(m.target,m.unit)}</span></div></div>`).join('')}
function renderPeople(){const el=$('#peopleGrid');el.innerHTML=state.people.map((p,pi)=>`<div class="person"><h4>${esc(p.name)}</h4><div class="checks">${[0,1].map(ci=>`<label class="check"><input type="checkbox" data-person="${pi}" data-check="${ci}" ${p.oneOnOnes[ci]?'checked':''}>1:1 ${ci+1}</label>`).join('')}</div></div>`).join('');$$('[data-person]').forEach(cb=>cb.onchange=async e=>{const pi=+e.target.dataset.person,ci=+e.target.dataset.check;state.people[pi].oneOnOnes[ci]=e.target.checked;await save()})}
function renderClients(){const rows=$('#clientRows');rows.innerHTML=state.croClients.length?state.croClients.slice().reverse().map((c,ri)=>{const idx=state.croClients.length-1-ri;return `<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.generated)}</td><td>${formatDate(c.date)}</td><td><button class="btn danger" data-del-client="${idx}">Excluir</button></td></tr>`}).join(''):`<tr><td colspan="4" style="color:#73808d">Nenhum cliente registrado.</td></tr>`;$$('[data-del-client]').forEach(b=>b.onclick=async()=>{state.croClients.splice(+b.dataset.delClient,1);await save()})}
function renderHistory(){const el=$('#weekHistory');el.innerHTML=state.weekly.length?state.weekly.slice().reverse().map((w,ri)=>{const idx=state.weekly.length-1-ri;return `<div class="week-card"><div class="week-top"><div><h4>${esc(w.name)}</h4><small>${formatDate(w.date)}</small></div><button class="btn danger" data-del-week="${idx}">Excluir</button></div>${w.note?`<div class="week-note">${esc(w.note)}</div>`:''}<div class="week-values">${state.metrics.map(m=>`<span class="mini">${esc(m.label)}: ${fmt(w.values?.[m.id],m.unit)}</span>`).join('')}</div></div>`}).join(''):`<div style="color:#73808d;font-size:13px">Nenhuma semana registrada ainda.</div>`;$$('[data-del-week]').forEach(b=>b.onclick=async()=>{if(confirm('Excluir este registro semanal?')){state.weekly.splice(+b.dataset.delWeek,1);await save()}})}
function renderChartSelect(){const sel=$('#chartMetric');const old=sel.value;sel.innerHTML=state.metrics.map(m=>`<option value="${m.id}">${esc(m.label)}</option>`).join('');if(state.metrics.some(m=>m.id===old))sel.value=old}
function renderChart(){if(typeof Chart==='undefined')return;const metric=state.metrics.find(m=>m.id===$('#chartMetric')?.value)||state.metrics[0];const mode=$('#chartMode')?.value||'actual';const labels=state.weekly.map(w=>w.name);let data=state.weekly.map(w=>w.values?.[metric.id]??null),target=state.weekly.map(()=>metric.target),yLabel=metric.unit;if(mode==='attainment'){data=state.weekly.map(w=>attainment(metric,w.values?.[metric.id]));target=state.weekly.map(()=>100);yLabel='%'}const ctx=$('#weeklyChart');if(!ctx)return;if(chart)chart.destroy();chart=new Chart(ctx,{type:'line',data:{labels,datasets:[{label:mode==='actual'?`${metric.label} realizado`:`${metric.label} — atingimento`,data,borderWidth:3,tension:.25,pointRadius:5,pointHoverRadius:7},{label:mode==='actual'?`Meta ${targetPrefix(metric)} ${fmt(metric.target,metric.unit)}`:'Meta 100%',data:target,borderWidth:2,borderDash:[6,6],pointRadius:0,tension:0}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom'},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${fmt(c.parsed.y,yLabel)}`}}},scales:{y:{beginAtZero:true,title:{display:true,text:yLabel}},x:{grid:{display:false}}}}})}
function nextWeek(){const n=state.weekly.length+1;$('#weekName').value=`Semana ${n}`;const d=new Date();if(state.weekly.length&&state.weekly[state.weekly.length-1].date){const prev=new Date(state.weekly[state.weekly.length-1].date+'T12:00:00');prev.setDate(prev.getDate()+7);$('#weekDate').value=prev.toISOString().slice(0,10)}else $('#weekDate').value=d.toISOString().slice(0,10)}
function formatDate(v){if(!v)return '—';const d=new Date(v+'T12:00:00');return new Intl.DateTimeFormat('pt-BR').format(d)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#nav').onclick=e=>{const b=e.target.closest('button[data-page]');if(!b)return;$$('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$('#page-'+b.dataset.page).classList.add('active');if(b.dataset.page==='weekly')setTimeout(renderChart,50)}
$('#saveMetrics').onclick=async()=>{state.metrics.forEach(m=>{const t=document.querySelector(`[data-metric-target="${m.id}"]`),u=document.querySelector(`[data-metric-unit="${m.id}"]`);if(t&&t.value!=='')m.target=Number(t.value);if(u)m.unit=u.value.trim()||m.unit});await save()}
$('#addWeek').onclick=async()=>{const name=$('#weekName').value.trim(),date=$('#weekDate').value,note=$('#weekNote').value.trim();if(!name||!date)return toast('Preencha semana e data');const values={};$$('[data-week-value]').forEach(i=>{if(i.value!=='')values[i.dataset.weekValue]=Number(i.value)});state.weekly.push({id:crypto.randomUUID?.()||String(Date.now()),name,date,note,values,createdAt:new Date().toISOString()});$('#weekName').value='';$('#weekDate').value='';$('#weekNote').value='';$$('[data-week-value]').forEach(i=>i.value='');await save();nextWeek()}
$('#fillNextWeek').onclick=nextWeek;
$('#addClient').onclick=async()=>{const name=$('#clientName').value.trim(),generated=$('#clientGenerated').value.trim(),date=$('#clientDate').value;if(!name||!generated)return toast('Preencha cliente e o que foi gerado');state.croClients.push({name,generated,date:date||new Date().toISOString().slice(0,10),createdAt:new Date().toISOString()});$('#clientName').value='';$('#clientGenerated').value='';await save()}
$('#chartMetric').onchange=renderChart;$('#chartMode').onchange=renderChart;
setInterval(async()=>{if(document.visibilityState==='visible'&&!saving){try{const r=await fetch(API,{cache:'no-store'});if(r.ok){const fresh=normalizeState(await r.json());if(fresh.updatedAt!==state.updatedAt){state=fresh;localStorage.setItem('painel60abaco',JSON.stringify(state));render();setSync('online')}}}catch{}}},12000);
nextWeek();$('#clientDate').value=new Date().toISOString().slice(0,10);load();
